# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := basic_decode
ARDUINO_LIBS := APRS-Decoder-Lib
ARDUINO_LIB_DIRS := $(shell pwd)/../../..
include ~/UnixHostDuino/UnixHostDuino.mk
